name: Publish to npm

on:
  release:
    types: [published]

env:
    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Clone repository
        uses: actions/checkout@v2

      # Install
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
          cache: 'npm'

      # Install dependencies
      - run: yarn

      # Lint and tests
      - run: yarn lint && yarn test
    
      # Build
      - run:  yarn build

      # Publish
      - run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          cd dist && npm publish --access public
